# Generated by Django 5.1.5 on 2025-10-04 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('is_continuacao', models.BooleanField(default=False)),
                ('nota_avaliacao', models.IntegerField(default=0)),
                ('descricao_avaliacao', models.TextField(default='')),
                ('compareceu_agendamento', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
