# Generated by Django 5.1.5 on 2025-10-04 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        ('funcionario', '0001_initial'),
        ('locacao', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='locacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locacao.locacao'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.servico'),
        ),
    ]
