# Generated by Django 5.1.5 on 2025-02-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='is_continuacao',
            field=models.BooleanField(default=False),
        ),
    ]
