# Generated by Django 5.1.5 on 2025-09-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agendamento_is_continuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='descricao_avaliacao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nota_avaliacao',
            field=models.IntegerField(default=0),
        ),
    ]
