# Generated by Django 5.1.5 on 2025-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='nota_avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
