# Generated by Django 5.1.5 on 2025-09-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_agendamento_descricao_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='identificador',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
