# Generated by Django 5.1.5 on 2025-10-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_agendamento_nota_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='descricao_avaliacao',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
