# Generated by Django 5.1.5 on 2025-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_agendamento_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='compareceu_agendamento',
            field=models.BooleanField(default=False),
        ),
    ]
