# Generated by Django 5.1.5 on 2025-10-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_agendamento_descricao_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
