# Generated by Django 5.1.5 on 2025-10-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_agendamento_compareceu_agendamento'),
        ('funcionario', '0003_alter_funcionario_foto'),
        ('locacao', '0001_initial'),
        ('servico', '0005_alter_servico_pontos_gerados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='locacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locacao.locacao'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.servico'),
        ),
    ]
