# Generated by Django 5.1.5 on 2025-10-04 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empresa', '0001_initial'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='funcionario.funcionario'),
        ),
    ]
