# Generated by Django 5.1.5 on 2025-11-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
