# Generated by Django 5.1.5 on 2025-09-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imagem_imagem'),
        ('empresa', '0003_empresa_criado_por'),
        ('funcionario', '0002_funcionario_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='funcionario.funcionario'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
