# Generated by Django 5.1.5 on 2025-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='identificador',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
