# Generated by Django 5.1.5 on 2025-10-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_cpf_cliente_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificador',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
