# Generated by Django 5.1.5 on 2025-10-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='duracao',
            field=models.IntegerField(blank=True, help_text='Em minutos', null=True),
        ),
    ]
