# Generated by Django 5.1.5 on 2025-09-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='receive_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
