# Generated by Django 5.1.5 on 2025-10-04 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao', models.CharField(blank=True, help_text='Em minutos', max_length=100, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pontos_resgate', models.IntegerField(blank=True, null=True)),
                ('pontos_gerados', models.IntegerField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_criados', to=settings.AUTH_USER_MODEL)),
                ('funcionarios', models.ManyToManyField(related_name='servicos', to='funcionario.funcionario')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
