# Generated by Django 5.1.5 on 2025-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.CharField(blank=True, help_text='Em minutos', max_length=100, null=True),
        ),
    ]
