# Generated by Django 5.1.5 on 2025-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_alter_funcionario_foto_alter_funcionario_nome'),
        ('servico', '0002_alter_servico_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='funcionarios',
            field=models.ManyToManyField(related_name='servicos', to='funcionario.funcionario'),
        ),
    ]
