# Generated by Django 5.1.5 on 2025-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_servico_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='pontos_gerados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servico',
            name='pontos_resgate',
            field=models.IntegerField(default=0),
        ),
    ]
