# Generated by Django 5.1.5 on 2025-09-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_servico_pontos_gerados_servico_pontos_resgate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='pontos_gerados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='pontos_resgate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
