# Generated by Django 5.1.5 on 2025-10-04 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.FloatField()),
                ('valor_cheio', models.FloatField()),
                ('is_promo', models.BooleanField()),
                ('porcentagem_promo', models.FloatField()),
                ('duracao_em_dias', models.IntegerField()),
                ('quantidade_empresas', models.IntegerField()),
                ('quantidade_funcionarios', models.IntegerField()),
                ('quantidade_locacoes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['valor_cheio'],
            },
        ),
        migrations.CreateModel(
            name='PlanoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adquirido_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano do Usuário',
                'verbose_name_plural': 'Planos dos Usuários',
            },
        ),
    ]
