# Generated by Django 5.1.5 on 2025-02-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('valor', models.FloatField()),
                ('duracao', models.IntegerField()),
                ('quantidade_servicos', models.IntegerField()),
                ('quantidade_funcionarios', models.IntegerField()),
                ('quantidade_clientes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
