# Generated by Django 5.1.5 on 2025-02-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='quantidade_clientes',
            new_name='quantidade_empresas',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='quantidade_servicos',
        ),
    ]
