# Generated by Django 5.1.5 on 2025-02-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0002_rename_quantidade_clientes_plano_quantidade_empresas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='duracao',
            new_name='duracao_em_dias',
        ),
        migrations.AlterField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
