# Generated by Django 5.1.5 on 2025-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0004_planousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='planousuario',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
