# Generated by Django 5.1.5 on 2025-10-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0005_planousuario_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='is_promo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='valor_cheio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
