# Generated by Django 5.1.5 on 2025-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0006_plano_is_promo_plano_valor_cheio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='porcentagem_promo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
