# Generated by Django 5.1.5 on 2025-10-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0007_plano_porcentagem_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['valor_cheio'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
    ]
