# Generated by Django 5.1.5 on 2025-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0008_alter_plano_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='quantidade_locacoes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
