# Generated by Django 5.1.5 on 2025-09-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagem_empresa_imagem_funcionario_and_more'),
        ('funcionario', '0002_funcionario_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto_funcionario', to='core.imagem'),
        ),
    ]
