# Generated by Django 5.1.5 on 2025-02-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('funcionario', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('cnpj', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('horario_abertura_dia_semana', models.TimeField()),
                ('horario_fechamento_dia_semana', models.TimeField()),
                ('para_almoço', models.BooleanField(default=False)),
                ('horario_pausa_inicio', models.TimeField(blank=True, null=True)),
                ('horario_pausa_fim', models.TimeField(blank=True, null=True)),
                ('horario_abertura_fim_de_semana', models.TimeField(blank=True, null=True)),
                ('horario_fechamento_fim_de_semana', models.TimeField(blank=True, null=True)),
                ('abre_sabado', models.BooleanField()),
                ('abre_domingo', models.BooleanField()),
                ('funcionarios', models.ManyToManyField(related_name='empresas', to='funcionario.funcionario')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='core.imagem')),
                ('servicos', models.ManyToManyField(related_name='servicos', to='servico.servico')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
