# Generated by Django 5.1.5 on 2025-10-04 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('funcionario', '0001_initial'),
        ('locacao', '0001_initial'),
        ('servico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('Serviço', 'Serviço'), ('Locação', 'Locação')], default='Serviço', max_length=20)),
                ('cnpj', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('horario_abertura_dia_semana', models.TimeField()),
                ('horario_fechamento_dia_semana', models.TimeField()),
                ('para_almoco', models.BooleanField(default=False)),
                ('horario_pausa_inicio', models.TimeField(blank=True, null=True)),
                ('horario_pausa_fim', models.TimeField(blank=True, null=True)),
                ('horario_abertura_fim_de_semana', models.TimeField(blank=True, null=True)),
                ('horario_fechamento_fim_de_semana', models.TimeField(blank=True, null=True)),
                ('abre_sabado', models.BooleanField()),
                ('abre_domingo', models.BooleanField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_criadas', to=settings.AUTH_USER_MODEL)),
                ('funcionarios', models.ManyToManyField(blank=True, related_name='empresas', to='funcionario.funcionario')),
                ('locacoes', models.ManyToManyField(blank=True, related_name='empresas', to='locacao.locacao')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='core.imagem')),
                ('servicos', models.ManyToManyField(blank=True, related_name='servicos', to='servico.servico')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
