# Generated by Django 5.1.5 on 2025-02-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('horario_abertura_dia_semana', models.TimeField()),
                ('horario_fechamento_dia_semana', models.TimeField()),
                ('horario_abertura_fim_de_semana', models.TimeField()),
                ('horario_fechamento_fim_de_semana', models.TimeField()),
                ('abre_sabado', models.BooleanField()),
                ('abre_domingo', models.BooleanField()),
                ('servicos', models.ManyToManyField(related_name='servicos', to='servico.servico')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
