# Generated by Django 5.1.5 on 2025-02-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
