# Generated by Django 5.1.5 on 2025-10-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cnpj',
        ),
    ]
