# Generated by Django 5.1.5 on 2025-10-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_remove_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
