# Generated by Django 5.1.5 on 2025-09-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_empresa_criado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='para_almoço',
            new_name='para_almoco',
        ),
    ]
