# Generated by Django 5.1.5 on 2025-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_nome'),
        ('funcionario', '0002_alter_funcionario_foto_alter_funcionario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='funcionarios',
            field=models.ManyToManyField(related_name='empresas', to='funcionario.funcionario'),
        ),
    ]
