# Generated by Django 5.1.5 on 2025-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_empresa_funcionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='horario_pausa_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='horario_pausa_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='para_almoço',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='horario_abertura_fim_de_semana',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='horario_fechamento_fim_de_semana',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
