# Generated by Django 5.1.5 on 2025-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_bairro_empresa_cidade_empresa_estado_and_more'),
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='locacoes',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='locacao.locacao'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('servico', 'Serviço'), ('locacao', 'Locação')], default='servico', max_length=20),
        ),
    ]
