# Generated by Django 5.1.5 on 2025-10-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_empresa_locacoes_empresa_tipo'),
        ('servico', '0005_alter_servico_pontos_gerados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='servicos', to='servico.servico'),
        ),
    ]
