# Generated by Django 5.1.5 on 2025-10-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_alter_empresa_servicos'),
        ('funcionario', '0003_alter_funcionario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='funcionario.funcionario'),
        ),
    ]
