# Generated by Django 5.1.5 on 2025-10-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_alter_empresa_funcionarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('Serviço', 'Serviço'), ('Locação', 'Locação')], default='Serviço', max_length=20),
        ),
    ]
