# Generated by Django 5.1.5 on 2025-02-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='hash_mercadopago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
