# Generated by Django 5.1.5 on 2025-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_remove_pagamento_empresa_pagamento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX')], max_length=255),
        ),
    ]
