# Generated by Django 5.1.5 on 2025-02-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0005_alter_pagamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-25 19:16'),
            preserve_default=False,
        ),
    ]
