# Generated by Django 5.1.5 on 2025-02-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0006_pagamento_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='created_at',
        ),
    ]
