# Generated by Django 5.1.5 on 2025-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0007_remove_pagamento_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
